name: Create Branch on Sprint Start

on:
  jira:
    types: [jiraSprintStarted]
    
  issues:
    types: [opened, reopened]
    labels:
      - PH 
      
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: Create branch in repository 1
      run: |
        git clone https://github.com/abhishekpandey108/CASL-React.git
        cd CASL-React
        # Replace <BRANCH_NAME_PREFIX> with a prefix for the branch name, e.g. "sprint-" (without quotes).
        # Replace <ISSUE_NUMBER> with the issue number of the sprint issue in Jira.
        # Replace <GITHUB_ACTOR> with your GitHub username.
        branch_name="sprint-1-${abhishekpandey108}"
        git checkout -b "$branch_name"
        git push --set-upstream origin "$branch_name"
   
    # Add additional steps for each repository you want to create a branch in.
